import { QuartzConfig } from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"

const config: QuartzConfig = {
  configuration: {
    pageTitle: "Rati Study Log",
    pageTitleSuffix: " | Rati Study Log",
    enableSPA: true,
    enablePopovers: true,
    analytics: null,
    locale: "ko-KR",
    baseUrl: "kdongsu5509.github.io/rati_study_log",
    ignorePatterns: [
      "private",
      "templates",
      ".obsidian",
      ".claude",
      ".github",
      "copilot",
      "node_modules",
      "public",
      ".quartz-cache",
      "quartz",
      "**/.trash/**",
      "package.json",
      "package-lock.json",
      "tsconfig.json",
      "tsconfig.tsbuildinfo",
      "quartz.config.ts",
      "quartz.layout.ts",
      "globals.d.ts",
      "index.d.ts",
      ".npmrc",
      ".node-version",
      ".prettierrc",
      ".prettierignore",
      ".gitattributes",
      ".gitignore",
    ],
    defaultDateType: "modified",
    theme: {
      fontOrigin: "googleFonts",
      cdnCaching: true,
      typography: {
        header: "Inter",
        body: "Inter",
        code: "JetBrains Mono",
      },
      colors: {
        lightMode: {
          light: "#ffffff",
          lightgray: "#e0e0e0",
          gray: "#7a7a7a",
          darkgray: "#1d1d1f",
          dark: "#1d1d1f",
          secondary: "#0066cc",
          tertiary: "#0071e3",
          highlight: "rgba(0, 102, 204, 0.08)",
          textHighlight: "#fff23688",
        },
        darkMode: {
          light: "#1d1d1f",
          lightgray: "#3a3a3c",
          gray: "#86868b",
          darkgray: "#f5f5f7",
          dark: "#ffffff",
          secondary: "#2997ff",
          tertiary: "#0a84ff",
          highlight: "rgba(41, 151, 255, 0.12)",
          textHighlight: "#b3aa0288",
        },
      },
    },
  },
  plugins: {
    transformers: [
      Plugin.FrontMatter(),
      Plugin.CreatedModifiedDate({
        priority: ["frontmatter", "git", "filesystem"],
      }),
      Plugin.SyntaxHighlighting({
        theme: {
          light: "github-light",
          dark: "github-dark",
        },
        keepBackground: false,
      }),
      Plugin.ObsidianFlavoredMarkdown({ enableInHtmlEmbed: false }),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.TableOfContents(),
      Plugin.CrawlLinks({ markdownLinkResolution: "shortest" }),
      Plugin.Description({ descriptionLength: 200, replaceExternalLinks: true }),
      Plugin.Latex({ renderEngine: "katex" }),
    ],
    filters: [Plugin.RemoveDrafts(), Plugin.RemoveRawTitles()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentPage(),
      Plugin.FolderPage(),
      Plugin.TagPage(),
      Plugin.ContentIndex({
        enableSiteMap: true,
        enableRSS: true,
        rssLimit: 50,
        rssFullHtml: false,
        includeEmptyFiles: false,
      }),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.Favicon(),
      Plugin.NotFoundPage(),
      Plugin.CustomOgImages(),
      Plugin.RobotsTxt(),
    ],
  },
}

export default config
